# Generated by Django 2.2.2 on 2019-06-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametro',
            new_name='Parametros',
        ),
    ]
