# Generated by Django 2.2.2 on 2019-06-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190626_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametros',
            new_name='Parametro',
        ),
    ]
