# Generated by Django 2.2.2 on 2019-06-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190626_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModRotativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('valor_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parametro')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Veiculo')),
            ],
        ),
    ]
