# Generated by Django 2.2.2 on 2019-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
