# Generated by Django 2.2.2 on 2019-07-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movmensalista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModRotativo',
            new_name='MovRotativo',
        ),
    ]
